language: node_js
node_js:
- '4.1'
# whitelist
before_install:
 - npm install -g npm@'>=3.3.12'
 - npm install -g bower karma-cli
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
before_script:
 - bower install
 - gulp build
