language: node_js

notifications:
  email: false

node_js:
  - '7'
  - '6'
  - '5'

before_install:
 - npm prune

script:
  - npm run test

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
  only:
    - master
